version: '3.7'

services:
  api:
    build:
      context: ./executer
    volumes:
      - static_root:/app/static_root
    env_file:
      - .env.main
    depends_on:
      - db
  
  executer:
    build:
      context: ./executer
      dockerfile: Dockerfile.exec
    volumes:
      - static_root:/app/static_root
    env_file:
      - .env.main
    depends_on:
      - api
      - db

  nginx:
    build: ./executer/nginx
    ports:
      - "80:80"
    volumes:
    - static_root:/static_root
    depends_on:
      - api
      - db
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  static_root:
  postgres_data: