# Generated by Django 4.1.1 on 2022-09-25 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InProcessJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execute.jobqueue')),
            ],
        ),
    ]
