#!/bin/sh

pipenv sync
pipenv run python manage.py makemigrations
pipenv run python manage.py migrate
pipenv run python manage.py collectstatic --noinput
exec pipenv run gunicorn executer.wsgi:application --bind 0.0.0.0:8001